version: '3.8'

services:
  app:
    build: ./app/
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - db
    environment:
      - FLASK_HOST=0.0.0.0

  db:
    image: postgres
    volumes:
      - dev_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dev

volumes:
  dev_db_data:
